repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.3
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/rbubley/mirrors-prettier
  rev: v3.6.2
  hooks:
    - id: prettier
      files: ^ui/
      types_or: [javascript, vue]
