# Generated by Django 4.2.20 on 2025-05-07 15:51

from django.db import migrations, models
import grimoirelab.core.models
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', grimoirelab.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', grimoirelab.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
